import localFont from "next/font/local";

import "./globals.css";

const Trap = localFont({
  src: [
    {
      path: "./fonts/Trap-Regular.otf",
      weight: "400",
    },
    {
      path: "./fonts/Trap-Medium.otf",
      weight: "500",
    },
    {
      path: "./fonts/Trap-Bold.otf",
      weight: "700",
    },
  ],
  variable: "--font-primary",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Trap.variable} font-sans bg-black text-white`}>
        {children}
      </body>
    </html>
  );
}
